### ISSUE TITLE
Performance on Apple Silicon

### ISSUE THREAD

**Issue by brookman** [RustCrypto/AEADs#601]
Hi. Thanks for providing the awesome crypto crates! 🦀
I was experimenting with the ChaCha20Poly1305 crate and found it to run 4x slower on a Mac with M1 CPU compared to an older Intel i7 Mac. Now I‘m wondering if this is a general issue with Rust (it seems that the arm64/AArch64-Apple-Darwin target is not tier 1 yet) or if there are specific optimizations in the RustCrypto crates for Intel. Or maybe I‘m missing a feature flag? Could somebody give me a hint here?

Thanks in advance!

**Comment by tarcieri** [comment]
The `chacha20` and `poly1305` crates have AVX2-optimized implementations on Intel. On ARM64 we use a portable software implementation instead and have no SIMD support other than what LLVM's auto-vectorization might be doing.

The `aes-gcm` crate, on the other hand, supports ARMv8 hardware acceleration for AES and GCM (i.e. PMULL) and will get you better results on M1.

**Comment by brookman** [comment]
Thank you for the hint @tripplet !
I'm trying to enable it by adding the following to my .cargo/config.toml file:

```toml
[target.aarch64-linux-android]
rustflags = ["-C", "target-feature=+neon", "--cfg", "chacha20_force_neon"]

[target.aarch64-apple-ios]
rustflags = ["-C", "target-feature=+neon", "--cfg", "chacha20_force_neon"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-feature=+neon", "--cfg", "chacha20_force_neon"]
```
Am I doing this correctly?
